on:
  push:
    paths:
      - 'ndn-all/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Set Version
      run: |
        echo "version=$(date +%Y%m%d%H%M)" > $GITHUB_ENV
    - name: Build and Push ndn-all Docker Image
      if: contains(github.event.head_commit.message, '[ndn-all]')
      run: |
        docker build -t hydrokhoos/ndn-all:$version ./ndn-all/
        docker push hydrokhoos/ndn-all:$version
