on:
  push:
    paths:
      - 'ndn-all/**'
  workflow_dispatch:
    inputs:
        image_to_build:
          description: 'Select the Docker image to build'
          required: true
          type: choice
          options:
            - ndn-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: hydrokhoos/ndn-all
        tags: |
          type=schedule,pattern={{date 'YYYYMMDDhhmm' tz='Asia/Tokyo'}}
          type=raw,value=latest
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and Push ndn-all Docker Image
      if: contains(github.event.head_commit.message, '[push ndn-all]') || github.event.inputs.image_to_build == 'ndn-all'
      uses: docker/build-push-action@v5
      with:
        file: ./ndn-all/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
