on:
  push:
    paths:
      - 'ndn-all/Dockerfile'
      - 'ipfs-test/Dockerfile'
  workflow_dispatch:
    inputs:
      image_to_build:
        description: 'Select the Docker image to build'
        required: true
        type: choice
        options:
          - ndn-all
          - ipfs-test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            hydrokhoos/ndn-all
            hydrokhoos/ipfs-test
          tags: |
            type=schedule,pattern={{date 'YYYYMMDDhhmm' tz='Asia/Tokyo'}}
            type=raw,value=latest
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Determine changed Dockerfile
        id: changed-file
        run: |
          if [ $(git diff --name-only HEAD^ HEAD | grep 'Dockerfile') == "ndn-all/Dockerfile" ]; then
            echo "::set-output name=dockerfile::ndn-all/Dockerfile"
            echo "::set-output name=image::hydrokhoos/ndn-all"
          elif [ $(git diff --name-only HEAD^ HEAD | grep 'Dockerfile') == "ipfs-test/Dockerfile" ]; then
            echo "::set-output name=dockerfile::ipfs-test/Dockerfile"
            echo "::set-output name=image::hydrokhoos/ipfs-test"
          else
            echo "::set-output name=dockerfile::${{ github.event.inputs.image_to_build }}/Dockerfile"
            echo "::set-output name=image::hydrokhoos/${{ github.event.inputs.image_to_build }}"
          fi

      - name: Build and Push Docker Image
        if: steps.changed-file.outputs.dockerfile != '' || github.event.inputs.image_to_build != ''
        uses: docker/build-push-action@v5
        with:
          file: ${{ steps.changed-file.outputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          repository: ${{ steps.changed-file.outputs.image }}
